# Generated by Django 4.2.4 on 2023-08-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
                (
                    "public_toilet",
                    models.BooleanField(default=True, verbose_name="public_toilet"),
                ),
                (
                    "accessible_by_walking_stick",
                    models.BooleanField(
                        default=False, verbose_name="accessible_by_walking_stick"
                    ),
                ),
                (
                    "accessible_by_wheel_chair",
                    models.BooleanField(
                        default=False, verbose_name="accessible_by_wheel_chair"
                    ),
                ),
                (
                    "accessible_by_wheel_chair_with_help",
                    models.BooleanField(
                        default=False,
                        verbose_name="accessible_by_wheel_chair_with_help",
                    ),
                ),
                (
                    "priority_parking",
                    models.BooleanField(default=False, verbose_name="priority_parking"),
                ),
                (
                    "mobility_impairment_facilities",
                    models.BooleanField(
                        default=False, verbose_name="mobility_impairment_facilities"
                    ),
                ),
                (
                    "visual_impdairment_facilities",
                    models.BooleanField(
                        default=True, verbose_name="visual_impairment_facilities"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="rating")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite", models.BooleanField(verbose_name="favorite")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
